export const PRODUCT_MIN_INVESTMENT_KRW = 10_000;
export const PRODUCT_MAX_INVESTMENT_KRW = 1_000_000;

export const PRODUCT_COMPANY_DIVIDEND_TRANSFER_RATE = 0.2;
export const PRODUCT_ANNUAL_INVESTOR_DIVIDEND_CAP_RATE = 0.1;
export const PRODUCT_MONTHLY_INVESTOR_DIVIDEND_CAP_RATE =
  PRODUCT_ANNUAL_INVESTOR_DIVIDEND_CAP_RATE / 12;
